### ISSUE TITLE
`noindex` property in content md sets `seo:indexing` 

### ISSUE THREAD

**Issue by martyf** [aerni/statamic-advanced-seo#93]
When a content md file has a noindex property, regardless of its value, the value of `seo:indexing` is set to `noindex`.

This means that pages output:
`<meta name="robots" content="noindex">`

See demo site:
https://github.com/martyf/statamic-advanced-seo-noindex

Stripped back content, with:
- Home page, behaving correctly (i.e. no "noindex" output)
- Three "noindex" variants with different values for the property, but all output the noindex robots tag

**Comment by aerni** [comment]
Ok, I think I found the issue. I'm pretty sure this was introduced with v2.0 of this addon. There was a substantial change in how the SEO data is hydrated.

Whatever data is in the view's context will be used to build the SEO cascade:

https://github.com/aerni/statamic-advanced-seo/blob/e8f89d202d6dfd3d5d2d20840071ae17d398a631/src/ServiceProvider.php#L189-L202

If `noindex` is in an entry's data, it will be picked up by this method that takes care of overriding certain values with their counterparts in the defaults. E.g. Making sure `noindex` is applied globally if it is set in the site defaults. This used to work fine before the new hydration approach introduced in v2.0.

https://github.com/aerni/statamic-advanced-seo/blob/e8f89d202d6dfd3d5d2d20840071ae17d398a631/src/View/BaseCascade.php#L85-L102

To fix this issue, I might have to take a whole different approach or do some nasty fixing. I'll have to take a closer look.

I don't think this issue is a showstopper either. There shouldn't be a `noindex` field in an entry anyways.

**Comment by martyf** [comment]
Thanks @aerni - I honestly don't know where these `noindex` properties came from - it's a site I've inherited and they've been there since the md files were originally created. Strange that it wasn't causing issues earlier.

**Comment by aerni** [comment]
The issue most likely started when the site was updated to use v2.0 of this addon. And the issue just went unnoticed for a while.

**Comment by aerni** [comment]
I took a closer look today and although this looks like a bug … it's actually a feature. There's no way to fix it without a major refactoring of how the addon works under the hood. Simply put, `noindex` is a reserved key. Make sure you don't use it.

**Comment by aerni** [comment]
I ran into this again today. It turns out, it was a bug after all with an easy fix.
