### ISSUE TITLE
1200px x 628px not large enough for OG image to be shown as "large image"

### ISSUE THREAD

**Issue by tobimori** [aerni/statamic-advanced-seo#97]
![CleanShot 2023-08-23 at 19 53 30@2x](https://github.com/aerni/statamic-advanced-seo/assets/29142128/0c7da86d-1b2e-4a19-9d66-7047445ceb34)
This is the current information in the Advanced SEO UI.
However, when uploading a image with 1200px x 628px, it will be shown in small in many clients.

Discord example
![CleanShot 2023-08-23 at 19 54 04@2x](https://github.com/aerni/statamic-advanced-seo/assets/29142128/4935ef34-7e2b-4004-bbc6-2fda91556eee)

Telegram example
![CleanShot 2023-08-23 at 19 54 23@2x](https://github.com/aerni/statamic-advanced-seo/assets/29142128/df05b789-bde5-4bbc-af8c-304d47505c40)

I think the threshold is actually 1200x630px.

**Comment by aerni** [comment]
I don't have any control over the display size of different platforms. The `1200x628px` (or maybe `1200x630px` by now) is what Facebook uses. You can change the size in the config to whatever you want.

**Comment by tobimori** [comment]
It seems stupid to have a default value if it's not recognized by most of the platforms.

**Comment by aerni** [comment]
All this value does is resize your uploaded image. Even if your images weren't resized by this addon, your original image would still be resized differently on different platforms.

Twitter is an exception, as it doesn't use Open Graph but its own meta tags. So we can target that specifically. Open Graph is developed by Facebook, which is why this addon uses Facebook's size as the default.

Feel free to PR the change of the default value. In meantime, you can just change the value in the config.
